name: UI Tests

on: [push, pull_request]

jobs:
  ui-tests:
    name: Visual Regression
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade jupyterlab~=3.0 numpy bqplot matplotlib ipympl==0.8.0 ipyvolume scipy
          python -m pip install ".[test]"
          jlpm
          jlpm build
          jupyter labextension develop . --overwrite
          cd ui-tests
          jlpm install --frozen-lockfile
          cd ../tests/widget_lib
          pip install .

      - name: Install browser
        run: |
          cd ui-tests
          # Install only Chromium browser
          jlpm playwright install chromium

      - name: Launch Voila stability test server
        run: |
          cd ui-tests
          jlpm start-stability 2>&1 > /tmp/jupyterlab_server.log &          

      - name: Wait for Voila
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8868/
          timeout: 360000

      - name: Launch Voila
        run: |
          cd ui-tests
          # Mount a volume to overwrite the server configuration
          jlpm start 2>&1 > /tmp/jupyterlab_server.log &

      - name: Wait for Voila
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8866/
          timeout: 360000

      - name: Test
        run: |
          cd ui-tests
          jlpm run test

      - uses: iterative/setup-cml@v1

      - name: Publish Results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORT: ./benchmark-results/voila-benchmark.md
        shell: bash
        run: |
          cd ui-tests

          # Publish image to cml.dev
          echo "" >> ${REPORT}
          cml-publish ./benchmark-results/voila-benchmark.png --md >> ${REPORT}
          echo "" >> ${REPORT}

          # Test if metadata have changed
          export METADATA_DIFF="/tmp/metadata.diff"
          diff -u <(jq --sort-keys .metadata benchmark-results/voila-benchmark.json) <(jq --sort-keys .metadata voila-benchmark-expected.json) > ${METADATA_DIFF} || true
          if [[ -s ${METADATA_DIFF} ]]; then
            echo "<details><summary>:exclamation: Test metadata have changed</summary>" >> ${REPORT}
            echo "" >> ${REPORT}
            echo "\`\`\`diff" >> ${REPORT}
            cat ${METADATA_DIFF} >> ${REPORT}
            echo "\`\`\`" >> ${REPORT}
            echo "" >> ${REPORT}
            echo "</details>" >> ${REPORT}
          fi

          # Save PR number for comment publication
          echo "${{ github.event.number }}" > ./benchmark-results/NR

      - name: Upload Playwright Test assets
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: voila-test-assets
          path: |
            ui-tests/test-results

      - name: Upload Playwright Benchmark report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: voila-benchmark-report
          path: |
            ui-tests/benchmark-results

      - name: Upload Playwright Test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: voila-test-report
          path: |
            ui-tests/playwright-report

      - name: Print JupyterLab logs
        if: always()
        run: |
          cat /tmp/jupyterlab_server.log

